gestion_proyectosmain_homepage:
    path:     /
    defaults: { _controller: gestionProyectosmainBundle:Default:index }
    
gestion_proyectosmain_create_user:
    path:     /registrarUsuario
    defaults: { _controller: gestionProyectosmainBundle:FormRegistroUsuario:createUsuario }
    
gestion_proyectosmain_login_user:
    path:     /loginUsuario
    defaults: { _controller: gestionProyectosmainBundle:FormLoginUsuario:loginUsuario }
    
gestion_proyectosmain_create_tarea:
    path:     /formTarea
    defaults: { _controller: gestionProyectosmainBundle:FormTarea:createTarea}
