<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS3ezafd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS3ezafd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerS3ezafd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerS3ezafd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerS3ezafd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'S3ezafd',
    'container.build_id' => '0a871ca3',
    'container.build_time' => 1520362414,
));
