<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLirxuwb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLirxuwb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLirxuwb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLirxuwb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLirxuwb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Lirxuwb',
    'container.build_id' => 'c73fa31d',
    'container.build_time' => 1519920134,
));
