<?php

namespace Proxies\__CG__\gestionProyectos\mainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tarea extends \gestionProyectos\mainBundle\Entity\Tarea implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'id', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'nombre', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'descripcion', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'fechainicio', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'fechafinal', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'status', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'idCreador'];
        }

        return ['__isInitialized__', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'id', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'nombre', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'descripcion', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'fechainicio', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'fechafinal', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'status', '' . "\0" . 'gestionProyectos\\mainBundle\\Entity\\Tarea' . "\0" . 'idCreador'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tarea $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', [$fechainicio]);

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', []);

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafinal($fechafinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafinal', [$fechafinal]);

        return parent::setFechafinal($fechafinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafinal', []);

        return parent::getFechafinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCreador(\gestionProyectos\mainBundle\Entity\Usuario $idCreador = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCreador', [$idCreador]);

        return parent::setIdCreador($idCreador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCreador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCreador', []);

        return parent::getIdCreador();
    }

}
